"""add season in tournamentteam model

Revision ID: 0520d69c623d
Revises: 71a7bf74a355
Create Date: 2026-05-29 13:46:34.141802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0520d69c623d'
down_revision: Union[str, Sequence[str], None] = '71a7bf74a355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_teams', sa.Column('season_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tournament_teams', 'seasons', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_teams', type_='foreignkey')
    op.drop_column('tournament_teams', 'season_id')
    # ### end Alembic commands ###
