"""add lazy selectin in model PlayerGalerey

Revision ID: 18352a02d0d0
Revises: e1ae16fc0149
Create Date: 2026-05-30 13:37:23.133400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18352a02d0d0'
down_revision: Union[str, Sequence[str], None] = 'e1ae16fc0149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
