"""update relationship

Revision ID: 329609d34bf3
Revises: 5a7959b18e66
Create Date: 2026-05-27 19:41:53.420911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329609d34bf3'
down_revision: Union[str, Sequence[str], None] = '5a7959b18e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('players_background_media_id_key'), 'players', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('players_background_media_id_key'), 'players', ['background_media_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
