"""add background_media_id to players

Revision ID: 5a7959b18e66
Revises: 291720efaf77
Create Date: 2026-05-27 19:26:40.966818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7959b18e66'
down_revision: Union[str, Sequence[str], None] = '291720efaf77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('background_media_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'players', ['background_media_id'])
    op.create_foreign_key(None, 'players', 'media_assets', ['background_media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'background_media_id')
    # ### end Alembic commands ###
