"""add role admin

Revision ID: eef4639d9eb5
Revises: ea9b8ba414fe
Create Date: 2026-05-22 16:37:50.071654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef4639d9eb5'
down_revision: Union[str, Sequence[str], None] = 'ea9b8ba414fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала создаём тип (если он ещё не существует)
    admin_role_enum = sa.Enum('SUPERADMIN', 'ADMIN', 'EDITOR', name='admin_role')
    admin_role_enum.create(op.get_bind(), checkfirst=True)
    
    # Теперь добавляем столбец, используя этот же тип
    op.add_column('admins', sa.Column('role', admin_role_enum, nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'role')
    # ### end Alembic commands ###
