"""initial

Revision ID: f394706da411
Revises: 
Create Date: 2026-05-20 00:23:15.372544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f394706da411'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('club_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('league_name', sa.String(length=255), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('results_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_table('parser_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='parser_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tournament_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('league_name', sa.String(length=255), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_teams_group_name'), 'tournament_teams', ['group_name'], unique=False)
    op.create_index(op.f('ix_tournament_teams_league_name'), 'tournament_teams', ['league_name'], unique=False)
    op.create_index(op.f('ix_tournament_teams_name'), 'tournament_teams', ['name'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('club_team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('match_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('our_score', sa.Integer(), nullable=True),
    sa.Column('opponent_score', sa.Integer(), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'FINISHED', 'POSTPONED', 'CANCELLED', name='match_status'), server_default='SCHEDULED', nullable=False),
    sa.Column('parsed_from_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_team_id'], ['club_teams.id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['tournament_teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_club_team_id'), 'matches', ['club_team_id'], unique=False)
    op.create_index(op.f('ix_matches_match_datetime'), 'matches', ['match_datetime'], unique=False)
    op.create_index(op.f('ix_matches_opponent_team_id'), 'matches', ['opponent_team_id'], unique=False)
    op.create_index(op.f('ix_matches_season_id'), 'matches', ['season_id'], unique=False)
    op.create_index(op.f('ix_matches_slug'), 'matches', ['slug'], unique=True)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cover_media_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_slug'), 'news', ['slug'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_team_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Enum('SETTER', 'LIBERO', 'MIDDLE_BLOCKER', 'OUTSIDE_HITTER', 'OPPOSITE', name='player_position'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('sport_rank', sa.String(length=255), nullable=True),
    sa.Column('avatar_media_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avatar_media_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['club_team_id'], ['club_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar_media_id')
    )
    op.create_index(op.f('ix_players_club_team_id'), 'players', ['club_team_id'], unique=False)
    op.create_index(op.f('ix_players_slug'), 'players', ['slug'], unique=True)
    op.create_table('standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sets_won', sa.Integer(), nullable=False),
    sa.Column('sets_lost', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(length=255), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['tournament_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standings_group_name'), 'standings', ['group_name'], unique=False)
    op.create_index(op.f('ix_standings_league_name'), 'standings', ['league_name'], unique=False)
    op.create_index(op.f('ix_standings_season_id'), 'standings', ['season_id'], unique=False)
    op.create_index(op.f('ix_standings_team_id'), 'standings', ['team_id'], unique=False)
    op.create_table('match_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('our_score', sa.Integer(), nullable=False),
    sa.Column('opponent_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_sets_match_id'), 'match_sets', ['match_id'], unique=False)
    op.create_table('player_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_gallery_media_asset_id'), 'player_gallery', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_player_gallery_player_id'), 'player_gallery', ['player_id'], unique=False)
    op.create_table('player_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('sets_played', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('attacks', sa.Integer(), nullable=False),
    sa.Column('aces', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_statistics')
    op.drop_index(op.f('ix_player_gallery_player_id'), table_name='player_gallery')
    op.drop_index(op.f('ix_player_gallery_media_asset_id'), table_name='player_gallery')
    op.drop_table('player_gallery')
    op.drop_index(op.f('ix_match_sets_match_id'), table_name='match_sets')
    op.drop_table('match_sets')
    op.drop_index(op.f('ix_standings_team_id'), table_name='standings')
    op.drop_index(op.f('ix_standings_season_id'), table_name='standings')
    op.drop_index(op.f('ix_standings_league_name'), table_name='standings')
    op.drop_index(op.f('ix_standings_group_name'), table_name='standings')
    op.drop_table('standings')
    op.drop_index(op.f('ix_players_slug'), table_name='players')
    op.drop_index(op.f('ix_players_club_team_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_news_slug'), table_name='news')
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_slug'), table_name='matches')
    op.drop_index(op.f('ix_matches_season_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_opponent_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_datetime'), table_name='matches')
    op.drop_index(op.f('ix_matches_club_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_tournament_teams_name'), table_name='tournament_teams')
    op.drop_index(op.f('ix_tournament_teams_league_name'), table_name='tournament_teams')
    op.drop_index(op.f('ix_tournament_teams_group_name'), table_name='tournament_teams')
    op.drop_table('tournament_teams')
    op.drop_table('seasons')
    op.drop_table('parser_runs')
    op.drop_table('media_assets')
    op.drop_table('club_teams')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
